name: moneyku
description: Aplikasi kelola keuangan pribadi
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase - gunakan versi terbaru
  supabase_flutter: ^2.6.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  # Chart
  fl_chart: ^0.69.0
  
  # Formatting
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"